'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Sparkles, Loader2, Copy, ChevronDown } from 'lucide-react'
import { toast } from '@/lib/toast'

interface RecordAIActionsProps {
  recordId: string
  aiEnabled?: boolean
}

export default function RecordAIActions({ recordId, aiEnabled = true }: RecordAIActionsProps) {
  const [loading, setLoading] = useState(false)
  const [summary, setSummary] = useState<string | null>(null)

  if (!aiEnabled) return null

  const handleSummarize = async () => {
    setLoading(true)
    setSummary(null)
    try {
      const res = await fetch('/api/ai/summarize', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ recordId }),
      })
      const data = await res.json()

      if (!res.ok) {
        if (res.status === 503) {
          toast.error('AI unavailable', data.error ?? 'AI features are not configured. Contact your administrator.')
        } else if (res.status === 403) {
          toast.error('AI disabled', data.error ?? 'AI features are disabled for this study. Contact the study admin to enable.')
        } else {
          toast.error('Summarization failed', data.error ?? 'An error occurred')
        }
        return
      }

      setSummary(data.summary)
      toast.success('Summary generated')
    } catch (e) {
      toast.error('Summarization failed', e instanceof Error ? e.message : 'An error occurred')
    } finally {
      setLoading(false)
    }
  }

  const handleCopy = async () => {
    if (!summary) return
    try {
      await navigator.clipboard.writeText(summary)
      toast.success('Copied to clipboard')
    } catch {
      toast.error('Copy failed', 'Could not copy to clipboard')
    }
  }

  return (
    <div className="space-y-3">
      <Button
        variant="outline"
        size="sm"
        onClick={handleSummarize}
        disabled={loading}
      >
        {loading ? (
          <>
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            Summarizing…
          </>
        ) : (
          <>
            <Sparkles className="mr-2 h-4 w-4" />
            Summarize with AI
          </>
        )}
      </Button>

      <details className="group">
        <summary className="flex cursor-pointer items-center gap-1 text-xs text-muted-foreground hover:text-foreground [&::-webkit-details-marker]:hidden">
          <ChevronDown className="h-3 w-3 group-open:rotate-180" />
          What we send to AI
        </summary>
        <p className="mt-1 text-xs text-muted-foreground">
          Record content (title, summary, notes, custom fields). No personal data or actor IDs.
        </p>
      </details>

      {summary && (
        <div className="rounded-md border-2 border-amber-200 bg-amber-50/50 p-3 text-sm dark:border-amber-900/50 dark:bg-amber-950/20">
          <div className="flex items-center justify-between gap-2 mb-2">
            <Badge variant="outline" className="bg-amber-100 text-amber-800 dark:bg-amber-900/50 dark:text-amber-200">
              AI-generated
            </Badge>
            <Button variant="ghost" size="sm" onClick={handleCopy} className="h-7 px-2">
              <Copy className="mr-1 h-3 w-3" />
              Copy
            </Button>
          </div>
          <p className="whitespace-pre-wrap">{summary}</p>
          <p className="mt-2 text-xs text-muted-foreground italic">
            This summary was generated by AI. Review before use. It is advisory only and has not been verified.
          </p>
        </div>
      )}
    </div>
  )
}
